### ISSUE TITLE
PackageManager, unable to see tabs

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/EvoFLAT#1]
css/tabpane.css (line 67)
Commenting out this line, everything works as expected.

**Comment by Nicola1971** [comment]
i dont have this issue. 
Is the Package Manager version from extras?
![download](https://user-images.githubusercontent.com/7342798/32569825-90691742-c4c2-11e7-8579-a73ebf8e967b.png)

**Comment by risingisland** [comment]
I think it is from [Jako's page](https://github.com/Jako/PackageManager), 1.0-RC4.
Which one should I be using?

**Comment by risingisland** [comment]
OK, just found http://extras.evolution-cms.com/packages/utilityi/packagemanager.html and did a file compare. This one works.
