### ISSUE TITLE
Color Scheme only effects user1

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/EvoFLAT#11]
When changing the color scheme (ex. "the header is dark"), other users scheme remains "header and sidebar are dark".
I even tried logging in from private/incognito modes, to see if it was a cache issue. Still remains remains "header and sidebar are dark".
Also gave user roll as Admin, no change.

**Comment by Nicola1971** [comment]
Checked: Seems an Evo issue.

When you create a manager user, the Color Scheme is the "current" color scheme in system settings (ie: header is dark) and does not use the "Default" (use manager system settings)

![screenshot-localhost-2019 03 11-16-29-45](https://user-images.githubusercontent.com/7342798/54135930-0d552380-441b-11e9-9e2f-4b4d515df35a.png)

this is why users created previously maintain the initial setting and do not update the color scheme when you change the setting in the system settings page

![screenshot-localhost-2019 03 11-16-32-28](https://user-images.githubusercontent.com/7342798/54136053-4f7e6500-441b-11e9-97f1-f400c3b97958.png)

**Solution**: You need to set all manager users to "Default" color scheme

**Comment by risingisland** [comment]
Solution works perfect.
I didnt even think of setting this for individual user.
Thanks for your time.
