### ISSUE TITLE
Firefox + Color Picker issue: Elements tab menu

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/EvoFLAT#4]
When you navigate to a section in Elements, everything is fine:
![my evolution site evo cms manager-01](https://user-images.githubusercontent.com/6113504/32650797-fe37f2ae-c5f6-11e7-8e37-6040b07bd98b.png)

...But if you select a different tab, then the current tabs background disappears:
![my evolution site evo cms manager-02](https://user-images.githubusercontent.com/6113504/32650843-292155c8-c5f7-11e7-8604-5bcd98eb78c0.png)

Also just noticed that the Page title changes too.

**Comment by Nicola1971** [comment]
Maybe a bug during conversion to css vars
Which browser? is the color picker disabled?
test the latest updates or RC6  and let me know if is fixed.
https://github.com/Nicola1971/EvoFLAT/releases/tag/RC6

you can try the Control Panel too 😃 
https://github.com/Nicola1971/EvoFLAT-SystemSettings

**Comment by Nicola1971** [comment]
note: delete previous version before update

**Comment by risingisland** [comment]
OK, just tried it out. 
The above problem still exists, but **only** when color picker is enabled.
Using Firefox. (with Chrome it seems to work fine either way)

**Comment by Nicola1971** [comment]
This bug seems exist only on Firefox and only when no Color Picker **Menu Color** is selected.
If you select a custom menu color, the problem disappear

**Comment by risingisland** [comment]
OK, I'm not going to worry about this one any more as I dont plan on using the color picker.
Will let you know if I find anything else.

Closing this ticket, but as you have tagged it as a bug, feel free to re-open it if need be.
