### ISSUE TITLE
Main menu problem

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/EvoFLAT#5]
So, it looks as though you are packaging this with EvoFLAT-SystemSettings now.
Mine as well include ZoomTree-Plugin too.

After install, the main menu is not displaying text or icons in either FF or Chrome...

![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/32888674-f308ba12-cabf-11e7-892d-cbe06d1a63a2.png)

Chrome also is not displaying Blue color layout for menu and links...

![chrome-flat](https://user-images.githubusercontent.com/6113504/32888735-353fd33e-cac0-11e7-8443-f6e656d9bf60.png)

**Comment by risingisland** [comment]
In the dev-branch, I think this has been resolved.
Will confirm this evening with a clean install.

On localhost, the package does not import the theme folder into the style folder.
I had to manually copy this over.

Question: Is there going to be one version of Flat that contains EvoFLAT-SystemSettings and one without, or are you going to merge these together?

**Comment by risingisland** [comment]
The theme problems seem to be caused by a caching issue with the plugins.
After install, if I re-enter config and save again, it seems to clear up the various problems.
I have done multiple clean installs and everything seems to point to this.

Loading the theme first will clear up most of these problems.
Unfortunately, I think everything worked smoother before it was moved to the config section.

**Comment by risingisland** [comment]
I think it is ok now.
Better with plugin separate from theme. (also good to know about Plugin Execution Order)

**Comment by risingisland** [comment]
Welcome page, welcome box icons, spacing is off (bumps last icon to next line):
![my evolution site evo cms manager](https://user-images.githubusercontent.com/6113504/32979342-51772cbe-cc4b-11e7-9659-3e2b87d2e5a7.png)


Suggest changing this line to 16%
https://github.com/Nicola1971/EvoFLAT/blob/e6e5f11f5be7f3bf681941c5959417a376845f0e/manager/media/style/EvoFLAT/css/custom.css#L273

**Comment by risingisland** [comment]
You may want to remove EvoFLAT-SystemSettings from readme?

**Comment by Nicola1971** [comment]
yes better the plugin as a separated package (allow more updates and fix)

The initial issue is caused by empy settings values (so everything goes ok when you save settings) -
 i'm working to fix

**Comment by Nicola1971** [comment]
about welcome widget - what resolution? (i think is 1024)

**Comment by risingisland** [comment]
Mine is at 1680, but I dont think that it is resolution dependent.
If there are 6 icons @16%=96%, as apposed to 6 icons @20%=120% forcing the last icon to drop down.
