### ISSUE TITLE
Show horizontal scroll in long tabs

### ISSUE THREAD

**Issue by 64j** [Nicola1971/EvoFLAT#6]
![image](https://user-images.githubusercontent.com/4653189/33222844-66ac603e-d16b-11e7-9ea7-23152f92bdc3.png)

**Comment by Nicola1971** [comment]
never noticied on big monitors. 
maybe related to the tab-row?

**Comment by Nicola1971** [comment]
seems fixed to me

**Comment by 64j** [comment]
@Nicola1971 
Then the touch will not work on mobile devices)

**Comment by Nicola1971** [comment]
ok, thanks.
i will check better tomorrow
