### ISSUE TITLE
Horizontal scroll in chunk edit mode width tinyMCE

### ISSUE THREAD

**Issue by AndreyMyagkov** [Nicola1971/EvoFLAT#7]
![horiz](https://user-images.githubusercontent.com/12766797/34342400-e764e5fc-e9d0-11e7-89f8-8fbb34c2d3ba.png)

**Comment by AndreyMyagkov** [comment]
Please add CSS rule in custom.css line #415
```
.tab-page .mce-panel:first-of-type {
    box-sizing: border-box;  /*add this */
}
```

**Comment by Nicola1971** [comment]
fixed. thanks
