### ISSUE TITLE
Аctive button not highlighted

### ISSUE THREAD

**Issue by AndreyMyagkov** [Nicola1971/EvoFLAT#8]
![button](https://user-images.githubusercontent.com/12766797/34342458-6c34a410-e9d2-11e7-90e8-c7f73444de31.png)

Аs an option to solve the problem I add this CSS rule into custom.css

`.mce-btn.mce-active, .mce-btn.mce-active:hover {
    border-color: #0f7fcc !important;
}`

**Comment by Nicola1971** [comment]
fixed. thanks
