### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/EvoFLAT#9]
Even when "everything is light" is selected in system config., theme is still dark.

**Comment by risingisland** [comment]
Will test this again later this afternoon. It may be an Evo problem, not switching to light.

**Comment by Nicola1971** [comment]
Is the same with the default theme. I think is just for users the default view.

**Comment by risingisland** [comment]
OK, I think I found what the problem is.
With the Flat theme, the config. options for "header and sidebar are dark" and "everything is dark" are reversed.
If you select "header and sidebar are dark" you end up getting "everything is dark"

**Comment by Nicola1971** [comment]
The new default theme and evo settings use darkness instead dark.
fixed in https://github.com/Nicola1971/EvoFLAT/releases/tag/1.0.4

you can update both theme and setting plugin from extras module

**Comment by risingisland** [comment]
Works like a charm, Thanks.
